# This job is a continuous integration pipeline that does stuff
# upon pushes of source code to the master branch of the repository. 
#
# Step 1
    # Analyze source code 
    # Run all python *.py files thru the linter
    # output: error report
    # decision: stop or proceed
    # (and other source code analysis tools)
# Step 2
    # Run test suite (pytest)
    # set up a virtual environment
    # output: pass or fail with errors
    # decision: stop or proceed
# Step 3
    # Run code coverage analysis https://about.codecov.io/?ref=hackernoon.com
# Step 4
    # Check data types (mypy)
# Step 5
    # Build a package ?? (pypa?)
# Step 6
    # Publish package ?? (pypi?)
# Step 7
    # send notification of results
# Step 8
    # Build and publish documentation
# Step 9
    # Check in code to repo


# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.11

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: execute tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
#            pytest -v --cov=calculator (maybe later)
            coverage run -m pytest
            coverage report
            mypy
